---
title: "Ingest all "
output: html_notebook
---

# Introduction
This file simply loads the raw data and performs preliminary data cleanup for later analysis.

Data to load:  

- List of elections.  
- First preference results.  
- Distribution of preferences.  
- Two candidate preferred.  
- Election polygons (for leaflet maps).  

```{r setup}
library(tidyverse)
library(rvest)
library(leaflet)
library(readxl)

library(plotly)

library(rgdal)    # Creates polygon for Northcote District map

data_dir <- ".././data"

elec_dates_flnm <- "Vic Elections.xlsx"

domain <- "https://www.vec.vic.gov.au/Results/State"
electorate_nm <- "Northcote"

first_pref_pg_nm <- "FPVbyVotingCentre"
# e.g. https://www.vec.vic.gov.au/Results/State2018/FPVbyVotingCentreNorthcoteDistrict.html
# e.g. https://www.vec.vic.gov.au/Results/state1999FPVbyVotingCentreNorthcoteDistrict.html

dist_pref_pg_nm <- "distribution"
# e.g. https://www.vec.vic.gov.au/Results/State2018/distributionNorthcoteDistrict.html
# Distribution data only starts from 2010.

two_cand_pref_1 <- "TCPbyVotingCentre"
two_cand_pref_2 <- "TCPbyVC"
# e.g. https://www.vec.vic.gov.au/Results/State2018/TCPbyVotingCentreNorthcoteDistrict.html
# e.g. https://www.vec.vic.gov.au/Results/state1999TCPbyVCNorthcoteDistrict.html

booth_addr_flnm <- "booth_addr.csv"

# Set up polygon names for Northcote District map
shp_dir <- "./data/SDM565161/ll_gda94/shape/state_assembly_2013/northcote-4000/VMADMIN"
dstrct_plgon_layer <- "STATE_ASSEMBLY_2013"
plgon_dist <- "NORTHCOTE"

# First preference page CSS selectors
first_pref_css_sels <- ".table-responsive td , .table-responsive th"

vote_cen_col_header <- "VOTING CENTRES"

```

# Import Election Years

```{r elec_dates}

elec_dates <- 
  read_excel(str_c(data_dir, elec_dates_flnm, sep = "/")) %>% 
  mutate(date = as.Date(date),
         elec_ID = as.character(elec_ID)) %>% 
  glimpse()

```

# Import first preference results

```{r first_pref}

years <- elec_dates$elec_ID

first_pref_lst <- vector("list", length(years)) %>% 
  set_names(years)

cands_lst <- vector("list", length(years)) %>% 
  set_names(years)

for (i in seq_along(first_pref_lst)) {
  # Step through each year for an election
  
  # i = 3
  yr <- years[[i]]
  first_pref_url <- str_c(domain, yr, "/", first_pref_pg_nm, electorate_nm, "District.html", sep = "")

  # Determine if URL is a valid page
  if (read_html(first_pref_url) %>% html_nodes(first_pref_css_sels) %>% length() == 0) {
    # Page address is invalid, try alternative address
    first_pref_url <- str_c(domain, yr, first_pref_pg_nm, electorate_nm, "District.html", sep = "")
    # i.e. it drops the "/" after the yr.
  }
      
  # first_pref_lst [[i]] <-
  first_pref <-
    read_html(first_pref_url) %>% 
    html_nodes(first_pref_css_sels) %>% 
    html_text() %>%
    keep(., ~ !str_detect(., "^[:blank:]")) 

  num_cols <- 
    first_pref %>% 
    detect_index(~ str_to_upper(.) %>% str_replace_all("\r\n", "") == vote_cen_col_header) - 1
  
  candidates <- c(first_pref[2:(num_cols - 2)])
  
  cand_party <- 
    first_pref[(num_cols + 2):(2 * num_cols - 2)] %>% 
    str_replace_all(., "\r\n", "") %>% 
    if_else(. == "", "INDEP", .)
  
  cands_lst[[i]] <- data.frame(candidates, cand_party, stringsAsFactors = FALSE)
    
  first_pref_lst [[i]] <- 
    first_pref %>%  
    matrix(., ncol = num_cols, byrow = TRUE,
           dimnames = list(seq(1:(length(first_pref) / num_cols)), 1:num_cols)) %>% 
    as_tibble() %>%
    tail(., -2) %>% # Remove the totals rows
    head(., -2) %>% # Remove the header rows
    set_names(c("booth", candidates, "informal", "total")) %>% 
    map_df(parse_guess) %>% 
    filter(!str_detect(booth, "Total")) %>% 
    select(-total) %>% 
    gather(key = "candidate", value = "votes", -booth)
  
}

cands <-
  bind_rows(cands_lst, .id = "year") %>% 
  rename(candidate = candidates) %>% 
  print()

first_pref <- 
  bind_rows(first_pref_lst, .id = "year") %>% 
  mutate(booth = str_remove_all(booth, "\\r\\n")) %>% 
  left_join(cands, by = c("year", "candidate")) %>% 
  print()

```

# Ingest Distribution of preferences

```{r}

distn_pref_css_sels <- ".table-responsive td , .table-responsive th"

dist_pref_urls <-
  elec_dates$elec_ID %>%
  map_chr(., ~ dist_pref_url_(domain, ., dist_pref_pg_nm, electorate_nm, distn_pref_css_sels)) %>%
  set_names(elec_dates$elec_ID) %>% 
  keep(., ~!is.na(.))

dist_lst <- vector("list", length(dist_pref_urls)) %>%
  set_names(names(dist_pref_urls))

pref_lst <- vector("list", length(dist_pref_urls)) %>% 
  set_names(names(dist_pref_urls))

for (i in seq_along(dist_pref_urls)) {
  # Step through each year for an election
  
  # i = 3
  yr <- names(dist_pref_urls)[i]
  
  dist_pref_url <- dist_pref_urls[i]
  
  # distn_yr_lst [[i]] <-
  distn_yr <-
    read_html(dist_pref_url) %>% 
    html_nodes(distn_pref_css_sels) %>% 
    html_text() %>% 
    keep(., ~ !str_detect(., "^[:blank:]"))
  
  num_cols <- 
    distn_yr %>% 
    detect_index(~ . == "TOTAL")
  
  candidates <- c(distn_yr[2:(num_cols - 1)])
  
  distn_raw <-
    # Table with measure, candidate and votes
    # measure is a combination of progressive totals and allocation of preferences
    distn_yr %>% 
    matrix(., ncol = num_cols, byrow = TRUE,
           dimnames = list(seq(1:(length(distn_yr) / num_cols)), 1:num_cols)) %>% 
    as_tibble() %>% 
    set_names(., c("measure", 
                   distn_yr[2:(num_cols - 1)], # %>% str_replace_all(., ", ", "_"),
                   "total")) %>% 
    select(-total) %>% 
    tail(., -1) %>% 
    gather("candidate", "votes", -measure) %>% 
    mutate(votes = parse_integer(votes)) %>% 
    filter(!is.na(votes))
  
  pref_lst[[i]] <-
    # Table showing how preferences were allocated
    distn_raw %>% 
    filter(str_detect(measure, "^Transfer of")) %>% 
    mutate(from_cand = str_replace(measure, "^.*ballot papers of ", "") %>% 
             str_replace(., " \\(.*", "")) %>% 
             # str_replace_all(., ", ", "_")) %>% 
    group_by(from_cand) %>% 
    mutate(votes_sum = sum(votes, na.rm = TRUE),
           votes_sh = votes / votes_sum) %>% 
    arrange(votes_sum, desc(votes_sh)) %>% 
    mutate(pref_rank = row_number()) %>% 
    select(from_cand, to_cand = candidate, votes, pref_rank, votes_sh, votes_sum) %>% 
    ungroup()
  
  dist_lst [[i]] <- 
    # Table showing number of votes after each round
    distn_raw %>% 
    filter(!str_detect(measure, "^Transfer of")) %>% 
    group_by(candidate) %>% 
    mutate(round = row_number(),
           received = votes - lag(votes)) %>% 
    select(candidate, round, votes, received) %>% 
    ungroup()
  
}

distn <- 
  bind_rows(dist_lst, .id = "year")

pref <-
  bind_rows(pref_lst, .id = "year")

```

